Repository fga-eps-mds/2020.1-eSaudeUnB-Wiki, pull requests merged in 2020-11, with the labels that each got.

#97 Documentação de fechamento da sprints 09 e planejamento da 10
  docs/img/burndown_sprint09.png
  docs/img/quadro_conhecimento_sprint_09.png
  docs/img/velocity_sprint09.png
  docs/planejamento_sprint08.md
  docs/planejamento_sprint10.md
  docs/planejamento_sprint9.md
  docs/resultado_sprint09.md
  mkdocs.yml
Labels: Scrum Master, documentation

#102 Resultado Sprint 10
  docs/img/burndown_sprint10.png
  docs/img/quadro_conhecimento_sprint10.png
  docs/img/velocity_sprint10.png
  docs/resultado_sprint10.md
  mkdocs.yml
Labels: EPS, Scrum Master, documentation, help wanted

#104 Atualizando EVM
  docs/resultado-sprint04.md
  docs/resultado-sprint3.md
  docs/resultado_sprint02.md
  docs/resultado_sprint05.md
  docs/resultado_sprint06.md
  docs/resultado_sprint07.md
  docs/resultado_sprint08.md
  docs/resultado_sprint09.md
  docs/resultado_sprint10.md
Labels: EPS, Scrum Master, documentation, enhancement

#108 Adição do planejamento e resultado referente a Sprint 11
  docs/img/burndown_sprint11.png
  docs/img/quadro_conhecimento_sprint11.png
  docs/img/velocity_sprint11.png
  docs/planejamento_sprint10.md
  docs/planejamento_sprint11.md
  docs/resultado_sprint05.md
  docs/resultado_sprint06.md
  docs/resultado_sprint07.md
  docs/resultado_sprint08.md
  docs/resultado_sprint09.md
  docs/resultado_sprint10.md
  docs/resultado_sprint11.md
  mkdocs.yml
Labels: EPS, Scrum Master, documentation

#114 resultado e planejamento da Sprint 12
  docs/img/burndown_sprint12.png
  docs/img/quadro_conhecimento_sprint12.png
  docs/img/velocity_sprint12.png
  docs/planejamento_sprint12.md
  docs/resultado_sprint11.md
  docs/resultado_sprint12.md
  mkdocs.yml
Labels: EPS, documentation
