Repository fga-eps-mds/2020.1-eSaudeUnB-Wiki, pull requests merged in 2020-10, with the labels that each got.

#78 Documento de fechamento da sprint 05 e planejamento da sprint 06
  docs/img/burndown_sprint05.png
  docs/img/quadro_conhecimento_05.png
  docs/img/velocity-sprint-03.png
  docs/img/velocity-sprint0.png
  docs/img/velocity-sprint02.png
  docs/img/velocity_sprint0.png
  docs/img/velocity_sprint01.png
  docs/img/velocity_sprint1.png
  docs/img/velocity_sprint2.png
  docs/img/velocity_sprint3.png
  docs/img/velocity_sprint4.png
  docs/img/velocity_sprint5.png
  docs/img/velocity_sprint_04.png
  docs/planejamento_sprint06.md
  docs/resultado-sprint04.md
  docs/resultado-sprint3.md
  docs/resultado_sprint0.md
  docs/resultado_sprint01.md
  docs/resultado_sprint02.md
  docs/resultado_sprint05.md
  mkdocs.yml
Labels: Scrum Master, documentation, important

#83 Criação da Apresentação da Release 1
  docs/release_01.md
  mkdocs.yml
Labels: EPS, Product Owner, documentation, help wanted, important

#84 docs: fix tags and images in documents
  docs/backlog.md
  docs/img/burndown-sprint0.png
  docs/img/burnout-sprint0.png
  docs/planejamento_sprint03.md
  docs/planejamento_sprint04.md
  docs/planejamento_sprint05.md
  docs/planejamento_sprint06.md
  docs/planejamento_sprint2.md
  docs/release_01.md
  docs/resultado-sprint04.md
  docs/resultado-sprint3.md
  docs/resultado_sprint0.md
  docs/resultado_sprint01.md
  docs/resultado_sprint02.md
  docs/resultado_sprint05.md
  mkdocs.yml
Labels: documentation

#85 Incorporar o vídeo da Apresentação da Release 1 no documento
  docs/release_01.md
Labels: EPS, documentation, hacktoberfest, hacktoberfest-accepted, important, improve

#86 Corrigir o vídeo incorporado
  docs/release_01.md
Labels: EPS, documentation, hacktoberfest, hacktoberfest-accepted

#87 Resultado Sprint 06
  docs/img/burndown_sprint_06.png
  docs/img/quadro_conhecimento_sprint_06.png
  docs/img/velocity_sprint_06.png
  docs/resultado_sprint06.md
  mkdocs.yml
Labels: EPS, Scrum Master, documentation, hacktoberfest, hacktoberfest-accepted

#89 Docs: Documento para avaliar valor agregado do projeto
  docs/evm.md
  mkdocs.yml
Labels: EPS, Scrum Master, documentation, hacktoberfest, hacktoberfest-accepted

#93 Documentação final das Sprints 07 e 08
  docs/img/burndown_sprint07.png
  docs/img/burndown_sprint08.png
  docs/img/velocity_sprint07.png
  docs/img/velocity_sprint08.png
  docs/planejamento_sprint07.md
  docs/planejamento_sprint08.md
  docs/resultado_sprint07.md
  docs/resultado_sprint08.md
  mkdocs.yml
Labels: EPS, Scrum Master, documentation
