Repository fga-eps-mds/2020.1-eSaudeUnB-Wiki, pull requests merged in 2020-08, with the labels that each got.

#14 Adicionado Documento de Gerência e Configuração de Software
  docs/gcs.md
  mkdocs.yml
Labels: documentation

#21 Fix/us06 translate
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: EPS, documentation

#22 Feature/us03 roadmap roles
  docs/img/architect.png
  docs/img/devops.png
  docs/img/productowner.png
  docs/img/scrummaster.png
  docs/index.md
  docs/roadmap-papeis.md
  mkdocs.yml
Labels: documentation

#25 docs: create code of conduct document #24
  CODE_OF_CONDUCT.md
Labels: EPS, documentation

#29 docs: fix docs formatting
  docs/gcs.md
  docs/tap.md
Labels: Bugfix, EPS, bug, documentation

#28 Feature/us08 mkdocs gh actions
  .github/workflows/ci.yml
  .travis.yml
Labels: DevOps, EPS
