Repository fga-eps-mds/2020.1-eSaudeUnB-Wiki, pull requests merged in 2020-09, with the labels that each got.

#30 fix: traduzindo o README
  README.md
Labels: EPS, Refactor, bug, documentation

#39 Documentação de planejamento e resultado da Sprint 0 e 1
  docs/img/burndown_sprint01.png
  docs/img/burnout-sprint0.png
  docs/img/quadro-sprint-0.png
  docs/img/velocity-sprint0.png
  docs/img/velocity_sprint01.png
  docs/planejamento_sprint0.md
  docs/planejamento_sprint01.md
  docs/resultado_sprint0.md
  docs/resultado_sprint01.md
  mkdocs.yml
Labels: EPS, Scrum Master, documentation

#49 Documentção da Sprint 02 e03
  docs/img/burndown-sprint02.png
  docs/img/quadro-conhecimento-sprint02.png
  docs/img/velocity-sprint02.png
  docs/planejamento_sprint03.md
  docs/planejamento_sprint2.md
  docs/resultado_sprint02.md
  mkdocs.yml
Labels: EPS, documentation

#40 docs: create product backlog document
  docs/backlog.md
  docs/img/backlog_futuro.png
  docs/img/backlog_presente.png
  docs/resultado_sprint0.md
  mkdocs.yml
Labels: EPS, Product Owner, documentation

#42 Elaboração da EAP
  docs/eap.md
  docs/img/eap.png
  mkdocs.yml
Labels: EPS, documentation, important

#51 Plano de Comunicação do Projeto
  docs/plano-de-comunicacao.md
  mkdocs.yml
Labels: EPS, Scrum Master, documentation

#53 Documento de Metodologia e Papeis
  docs/metodologia-e-papeis.md
  mkdocs.yml
Labels: EPS, Product Owner, documentation

#52 Docs/additional specification
  docs/DocumentoDeEspecificacaoSuplementar.md
  docs/img/diagrama_NFR.png
  mkdocs.yml
Labels: MDS, documentation, help wanted

#54 Prototipo de alta fidelidade
  docs/img/LoginPage.png
  docs/img/landingPage.png
  docs/img/patientList.png
  docs/img/patientResume.png
  docs/img/patientResumeNewResume.png
  docs/img/patientResumeShow.png
  docs/img/patientResumeShowAll.png
  docs/img/psychologistList.png
  docs/img/psychologistList_2.png
  docs/img/psychologistMain.png
  docs/img/psychologistProfile.png
  docs/img/signUP_01.png
  docs/img/signUP_02.png
  docs/img/userMain.png
  docs/img/userNewAtm.png
  docs/img/userNewAtmErr.png
  docs/img/userNewAtm_02.png
  docs/img/userprofile.png
  docs/prototipo_alta_fidelidade.md
  mkdocs.yml
Labels: MDS, documentation, good first issue, important

#60 docs: create product roadmap document #9
  docs/img/roadmap_primeira_release.png
  docs/roadmap_produto.md
  mkdocs.yml
Labels: EPS, Product Owner, documentation, important

#61 Docs/review sprint03
  docs/img/burndown_sprint_03.png
  docs/img/quadro-conhecimento-sprint03.png
  docs/img/velocity-sprint-03.png
  docs/resultado-sprint3.md
  mkdocs.yml
Labels: Scrum Master, documentation

#62 Plano de Gerenciamento de Riscos
  docs/burndown_risco.md
  docs/index.md
  docs/plano-gerenciamento-riscos.md
  mkdocs.yml
Labels: EPS, Product Owner, documentation, help wanted, important

#70 Documentação Planejamento da Sprint 04 e 05 e resultado da Sprint 05
  docs/img/burndown_sprint_04.png
  docs/img/quadro_conhecimento_sprint_04.png
  docs/img/velocity_sprint_04.png
  docs/planejamento_sprint03.md
  docs/planejamento_sprint04.md
  docs/planejamento_sprint05.md
  docs/resultado-sprint04.md
  mkdocs.yml
Labels: EPS, Scrum Master, documentation

#71 Plano de Qualidade do Projeto
  docs/plano-qualidade-projeto.md
  mkdocs.yml
Labels: EPS, Scrum Master, documentation, important

#72 Plano de gerenciamento de custo
  docs/img/pert.jpg
  docs/plano_gerenciamento_custo.md
  mkdocs.yml
Labels: EPS, Scrum Master, documentation

#73 docs: add pipeline plan
  docs/img/pipelinebackend.png
  docs/img/pipelinebackendcodeclimate.png
  docs/img/pipelinefrontend.png
  docs/img/pipelinefrontendcodeclimate.png
  docs/plano-pipeline.md
  mkdocs.yml
Labels: DevOps, EPS, documentation
